### ISSUE TITLE
kraken build typo

### ISSUE THREAD

**Issue by dpark01** [broadinstitute/viral-classify#20]
From @lakras:
```
+ metagenomics.py kraken2_build /home/dnanexus/tmp.cz7tNSRcma --tax_db=/home/dnanexus/tmp.doXVmDiwl0 --standard_libraries nr --taxdump_out taxdump-kraken2x-ncbi-full-nr-20160923.tar.gz --protein
2020-06-11 20:20:18,666 - cmd:197:main_argparse - INFO - software version: v2.1.3, python version: 3.6.7 | packaged by conda-forge | (default, Jul  2 2019, 02:18:42) 
[GCC 7.3.0]
2020-06-11 20:20:18,666 - cmd:199:main_argparse - INFO - command: /opt/viral-ngs/source/metagenomics.py kraken2_build db=/home/dnanexus/tmp.cz7tNSRcma tax_db=/home/dnanexus/tmp.doXVmDiwl0 taxdump_out=taxdump-kraken2x-ncbi-full-nr-20160923.tar.gz standard_libraries=['nr'] custom_libraries=None kmerLen=None minimizerLen=None minimizerSpaces=None protein=True maxDbSize=None threads=None loglevel=INFO tmp_dir=/home/dnanexus tmp_dirKeep=False
Downloading nr database from server... rsync: failed to connect to ftp.ncbi.nlm.nih.gov (130.14.250.12): Connection refused (111)
rsync: failed to connect to ftp.ncbi.nlm.nih.gov (2607:f220:41e:250::11): Cannot assign requested address (99)
rsync error: error in socket IO (code 10) at clientserver.c(127) [Receiver=3.1.3]
Traceback (most recent call last):
  File "/opt/viral-ngs/source/metagenomics.py", line 1564, in <module>
    util.cmd.main_argparse(__commands__, __doc__)
  File "/opt/viral-ngs/source/util/cmd.py", line 216, in main_argparse
    ret = args.func_main(args)
  File "/opt/viral-ngs/source/util/cmd.py", line 106, in _main
    mainfunc(**args2)
  File "/opt/viral-ngs/source/metagenomics.py", line 1466, in kraken2_build
    num_threads=threads)
  File "/opt/viral-ngs/viral-classify/classify/kraken2.py", line 88, in build
    fut.resuilt()
AttributeError: 'Future' object has no attribute 'resuilt'
```

**Comment by dpark01** [comment]
@lakras give the latest WDL rc a try?

**Comment by lakras** [comment]
So far so good! It's gotten farther than any of the others.

**Comment by lakras** [comment]
Thank you!!!!
